// Shared mutable application state.
// All modules import this same object, so mutations are visible everywhere.
export const state = {
    planetMesh: null,
    wireMesh: null,
    superPlateBorderMesh: null,
    mapSuperPlateBorderMesh: null,
    arrowGroup: null,
    windArrowGroup: null,
    curData: null,
    plateColors: {},
    _hoverBackup: null,
    hoveredPlate: -1,
    hoveredRegion: -1,
    hoveredKoppen: -1,
    _koppenHoverBackup: null,
    _mapKoppenHoverBackup: null,
    mapMesh: null,
    mapProjectionSnapshotMesh: null,
    _mapProjectionSnapshotTarget: null,
    mapFaceToSide: null,
    _mapHoverBackup: null,
    mapGridMesh: null,
    globeGridMesh: null,
    gridEnabled: true,
    gridSpacing: 15,
    mapMode: false,
    freeCameraMode: false,
    mapProjection: 'equirectangular',
    mapCenterLon: 0,
    mapCenterLat: 0,
    mapRotation: 0,
    mapZoom: 1,
    dragStart: null,
    debugLayer: '',
    isTouchDevice: ('ontouchstart' in window) || (navigator.maxTouchPoints > 0),
    editMode: false,
    oceanCurrentArrowGroup: null,
    climateComputed: false,
    pendingToggles: new Set(),
    _pendingBackup: null,
    _mapPendingBackup: null,
    importedHeightmap: false,
};
